config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'requests#index'
  resources :requests do
    resources :choices
    resources :responses
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :request
  has_many :responses

  validates :choice_text, presence: true

end

app/models/request.rb
class Request < ApplicationRecord
  has_many :responses
  has_many :choices
  belongs_to :user
  has_one_attached :image

  def total_responses()
    return self.responses.length
  end

  validates :question, :image, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :request
  belongs_to :choice 
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :requests
  has_many :responses


  def full_name
    return "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    User.find_by(id: session[:user_id])
  end

  def require_login
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to login_url
    end
  end


  helper_method :current_user

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController

  def new
    @choice = Choice.new
    @request = Request.find(params[:request_id])
  end

  def create
    @choice = Choice.new
    @request = Request.find(params[:request_id])

    @choice.choice_text = params[:choice][:choice_text]
    @choice.request_id = @request.id

    if @choice.save
      redirect_to new_request_choice_path(@request)
    else
      redirect_to request_path(@request)
    end

  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @requests = Request.all
  end

  def new
    @request = Request.new
    @choice = Choice.new
  end

  def create
    @request = Request.new
    @request.question = params[:request][:question]
    @request.image.attach(params[:request][:image])
    @request.user = current_user

    if @request.save
      redirect_to new_request_choice_path(@request)
    else
      render :new
    end
  end

  def show
    @request = Request.find(params[:id])
  end

  def update

  end

  def edit

  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def new
    @response = Response.new
    @request = Request.find(params[:request_id])
  end

  def create
    @response = Response.new
    @request = Request.find(params[:request_id])

    @response.user = current_user
    @response.request_id = @request.id
    @response.choice_id = params[:choice_id]
    @response.comment = params[:response][:comment]

    if @response.save
      redirect_to request_path(@request)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    flash[:previous_page] = request.referer
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      if flash[:previous_page] && flash[:previous_page] != :login
        redirect_to flash[:previous_page], notice: "Logged in!"
      else
      redirect_to root_path, notice: "Logged in!"
    end
    else
      flash[:notice] = "Login failed"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to request.referer, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new

    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    @user.status = params[:user][:status]

    if @user.save
      session[:user_id] = @user.id
      redirect_to requests_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @requests = @user.requests
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/choices/new.html.erb
<%= form_for([@request, @choice]) do |f| %>
<div class="choice">
  <%= f.label :choice %>
  <%= f.text_field :choice_text %>

  <%= f.submit 'Add choice', :class => "submit" %>
</div>

<%= link_to 'No more choices', requests_path, :class => "stop_choice" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feedbask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <div class="logo">
      <h1>FeedBask</h1>
      <p id = "subtittle">* Ask about design </p>
    </div>
    <div class="navbar">
      <%= link_to 'Home', requests_url %>
      <% if current_user %>
      <div class="profile">
        <%= link_to "#{current_user.first_name}", user_path(current_user) %>
      </div>
      <div class="create_request">
        <%= link_to "Create Question", new_request_path %>
      </div>
      <% else %>
      <div class="user_option">
        <%= link_to "Sign Up", new_user_path %>
        <%= link_to "Login",  new_session_path %>
        </div>
      <% end %>
    </div>
  </header>

  <body>
    <main>

    <%= yield %>

    </main>
    <footer> © <span> Nicolas Delforno </span> </footer>
  </body>
</html>

app/views/requests/index.html.erb
<% @requests.each do |request| %>
<% if !request.image %>
<% request.image = 'https://picsum.photos/200/300' %>
<% end %>
<div class="request">
  <%= link_to image_tag(request.image), new_request_response_path(request) %>
  <p><%= link_to "#{request.question}", new_request_response_path(request) %> created by: <%= request.user.full_name %></p>
</div>
<% end %>

app/views/requests/new.html.erb
<h1>New Question</h1>

  <%= form_for @request do |f| %>
  <div class="field">
    <p> <%= f.label :question  %> </P>
    <%= f.text_area :question %>
  </div>

  <div class="image_upload">
    <%= f.label :image  %>
    <%= f.file_field :image, :class => 'image_upload' %>
  </div>

  <div class="submit">
    <%= f.submit 'submit', :class => 'submit'%>
  </div>

  <% end %>

app/views/requests/show.html.erb
<div class="image">
<%= image_tag @request.image %>
</div>
<p><%= @request.question %></p>

app/views/responses/new.html.erb
  <%= form_for ([@request,@response]) do |f| %>

    <div class="image">
    <%= image_tag @request.image  %>
    </div>

    <div class="response">
      <div class="question">
        <%= @request.question  %>
      </div>


      <% @request.choices.each do |choice| %>
      <div class="choice">
        <%= radio_button_tag(:choice_id, "#{choice.id}") %>
        <%= label_tag(:choice_id, "#{choice.choice_text}") %>
      </div>
      <% end %>

      <div class="comment">
        <%= f.label :comment %>
        <%= f.text_field :comment %>
      </div>


      <%= f.submit 'submit', :class => "submit" %>

    </div>

  <% end %>

app/views/users/new.html.erb
<h1>Sign-up</h1>

<%= form_for @user do |f| %>
  <div class="field">
     <%= f.label :first_name %><br />
     <%= f.text_field :first_name %>
  </div>

  <div class="field">
     <%= f.label :last_name %><br />
     <%= f.text_field :last_name %>
  </div>

  <div class="field">
     <%= f.label :email %><br />
     <%= f.text_field :email %>
  </div>

  <div class="field">
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>

  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= radio_button_tag(:status, "Student") %>
    <%= label_tag(:status, "Student") %>
    <%= radio_button_tag(:status, "Instructor") %>
    <%= label_tag(:status, "Instructor") %>
  </div>

  <div class="field">
     <%= f.submit 'Sign-up', :class => 'submit' %>
  </div>

<% end %>

app/views/users/show.html.erb
<div class="info">
  <h1><%= @user.full_name %>
  <div class="logout">
      <% if current_user %>
      <%= link_to "Log Out", session_path(current_user), method: :delete %>
      <% end %>
  </div>
  </h1>
</div>

  <h2>Past requests:</h2>
  <hr>

<div class="history">
    <%@requests.each do |request| %>
    <div class="request">
      <div class="image">
        <%= image_tag request.image  %>
      </div>

      <div class="question">
        <h1><%= request.question %></h1>
      </div>

      <div class="Responses">
        <h2>Responses : <%= request.total_responses %></h2>
      </div>

      <div class="choices">
        <% request.choices.each do |choice| %>
        <p><%= choice.choice_text %> : <%= choice.responses.length %></p>
        <% end %>
      </div>

      <div class="comments">
        <h3>Comments: </h3>
        <%request.responses.each do |response| %>
        <ul>
          <% if response.comment.empty? == false %>
            <li> <%= response.comment %> </li>
          <% end %>
        </ul>
        <% end %>
      </div>
    </div>
  <% end %>
</div>